name: Docker Proxy
description: "Proxies the Docker.sock to enable container monitoring"
version: "0.3.0"
slug: dockerproxy
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
host_network: true
privileged: []
options: {}
schema: {}
image: "tecnativa/docker-socket-proxy"
ports:
  2375/tcp: 2375
volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
environment:
  BUILD: "1"
  COMMIT: "1"
  CONFIGS: "1"
  CONTAINERS: "1"
  DISTRIBUTION: "1"
  EXEC: "1"
  IMAGES: "1"
  INFO: "1"
  NETWORKS: "1"
  NODES: "1"
  PLUGINS: "1"
  SERVICES: "1"
  SESSSION: "1"
  SWARM: "1"
  SYSTEM: "1"
  TASKS: "1"
  VOLUMES: "1"
