name: dockerproxy
description: "Proxies the docker.sock to enable container monitoring"
version: "0.3.0"
slug: dockerproxy
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
host_network: true
privileged:
 - NET_ADMIN
 - SYS_ADMIN
 - DAC_READ_SEARCH
full_access: true
options: {}
schema: {}
image: "tecnativa/docker-socket-proxy"
ports:
  2375/tcp: 2375
volumes:
  - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Socket access
environment:
  BUILD: "1"
  COMMIT: "1"
  CONFIGS: "1"
  CONTAINERS: "1"
  DISTRIBUTION: "1"
  EXEC: "1"
  IMAGES: "1"
  INFO: "1"
  NETWORKS: "1"
  NODES: "1"
  PLUGINS: "1"
  SERVICES: "1"
  SESSION: "1"
  SWARM: "1"
  SYSTEM: "1"
  TASKS: "1"
  VOLUMES: "1"
