name: dockerproxy
description: "proxies the docker.sock to enable container monitoring"
version: "0.1.1"
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
slug: dockerproxy
boot: auto
options: {}
schema: {}
image: tecnativa/docker-socket-proxy
host_network: false
volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
ports:
  "2375/tcp": 2375