name: dockerproxy
description: "Proxies the docker.sock to enable container monitoring"
version: "0.3.0"
slug: dockerproxy
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
host_network: true
privileged: []
options: {}
schema: {}
image: "tecnativa/docker-socket-proxy"
ports:
  2375/tcp: 2375
volumes:
  - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Ensure socket is mounted here
environment:
  NETWORKS: "1"
  NODES: "1"
  PLUGINS: "1"
  SERVICES: "1"
  SESSION: "1"
  SWARM: "1"
  SYSTEM: "1"
  TASKS: "1"
  VOLUMES: "1"
  CONTAINERS: "1"
  EVENTS: "1"
  EXEC: "1"
  IMAGES: "1"
  SECRETS: "1"
  CONFIGS: "1"
  INFO: "1"
  AUTH: "1"
  BUILD: "1"
  DISTRIBUTION: "1"
  HEALTHCHECKS: "1"
  REGISTRIES: "1"
